version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/ims_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - JAVA_OPTS=-Xmx512m
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.ims.com
    environment:
      - GITLAB_OMNIBUS_CONFIG=external_url 'http://gitlab.ims.com'
    ports:
      - "443:443"
      - "80:80"
      - "22:22"
    volumes:
        - ./data/gitlab/config:/etc/gitlab
        - ./data/gitlab/logs:/var/log/gitlab
        - ./data/gitlab/data:/var/opt/gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    depends_on:
      - gitlab
    volumes:
      - ./data/gitlab-runner/config:/etc/gitlab-runner
      - ./data/gitlab-runner/data:/var/run/docker.sock



